### ISSUE TITLE
Reuse for testing in SharedWorker

### ISSUE THREAD

**Issue by dnoliver** [Joris-van-der-Wel/karma-mocha-webworker#2]
Hello @Joris-van-der-Wel, thank you for this plugin!

So I am currently working in a project that use Shared Workers, and I am the one that has to came up with unit testing framework for that code. I was using Karma + Mocha + Requirejs for browser code, and I started using Karma + Karma-Mocha-WebWorkers for the Shared Worker code. 

(NOTE: I spent a few ours trying to make requirejs work with this plugin, maybe I could post the HOW TO here)

My question is, do you think it is a valid idea to allow somebody to configure different types of Workers to be used to run the test? So I can use Web Worker, or Service Worker, or Shared Worker

Maybe I could do a PR for this

**Comment by Joris-van-der-Wel** [comment]
Sure! That would be great. Support for Shared Web Workers should be pretty easy to add. Just use the different constructor (`SharedWorker`), and generate an unique worker name.

I am not sure if Service Workers are possible with karma however. As far as I know, you have to reload the page after registering a Service Worker, and karma does not support reloading the page. I am also not sure what the effects would be of performing multiple test runs in the same browser instance/profile (for example using `karma --no-single-run`). For example, what if you install a service worker that accidentally breaks all requests to the karma server?

Feel free to add a short guide about requirejs to the [wiki](https://github.com/Joris-van-der-Wel/karma-mocha-webworker/wiki)

**Comment by dnoliver** [comment]
Apparently it is not just changing the constructor name :( I had to make several modifications to use onconnect and port.postMessage to make the communication work. But it is working finally :)

**Comment by dnoliver** [comment]
@Joris-van-der-Wel  I think I need some help :(

My Windows machine only has Chrome installed, and test are passing there. But 100% test fail in Travis. Apparently Karma cannot find shared-worker.js, do you see something wrong with the implementation?

**Comment by Joris-van-der-Wel** [comment]
Added in version 1.3.0
